### ISSUE TITLE
Stopped working after the recent update

### ISSUE THREAD

**Issue by armancohan** [steven2358/NuffTabs#10]
Chrome Version 128.0.6613.120

The extension stopped working after it was updated recently.
Sometimes when I restart chrome, it starts working, but after a while it stops working again.

I noticed this error in the logs.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'created')
    at background.js:157:41
    at Array.reduce (<anonymous>)
    at selectTabToClose (background.js:156:24)
    at enforceTabLimit (background.js:80:32)
    at async background.js:115:3
```

**Comment by steven2358** [comment]
Should be solved now. cbefcf8
